version: '3'

services:
  gentoo:
    build: ./gentoo
    container_name: gentoo-elivepatch
    restart: always
  
  debian:
    build: ./debian
    container_name: debian-elivepatch
    restart: always
