version: '3'

services:
  gentoo:
    build: ./gentoo
    container_name: gentoo-elivepatch
    restart: always
    ports:
      - 5000:5000
    volumes:
      - elivepatch_data:/tmp/

volumes:
  elivepatch_data:
